-- YouTube 일일 트렌드 데이터를 저장하기 위한 테이블 생성 스키마
-- Supabase Dashboard -> SQL Editor에 복사하여 실행하세요.

CREATE TABLE daily_trends (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,                                     -- 분석 기준일 (예: 2026-01-13)
    keyword TEXT NOT NULL,                                 -- 검색 키워드
    video_count INT,                                       -- 전날 업로드된 영상 수
    total_views BIGINT,                                    -- 총 조회수 합계
    total_likes BIGINT,                                    -- 총 좋아요 합계
    total_comments BIGINT,                                 -- 총 댓글 합계
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()), -- 기록 생성 시간
    
    -- 동일 날짜와 키워드에 대해 중복 데이터를 방지하기 위한 제약 조건
    UNIQUE(date, keyword)
);

-- 인덱스 추가 (검색 속도 향상)
CREATE INDEX idx_daily_trends_date ON daily_trends(date);
CREATE INDEX idx_daily_trends_keyword ON daily_trends(keyword);
