-- [설명] YouTube 일일 트렌드 데이터를 저장하기 위한 방(Table)을 만드는 코드입니다.
-- [방법] Supabase 사이트 접속 -> SQL Editor -> 새 쿼리창에 아래 내용을 복사해서 실행(Run) 하세요.

CREATE TABLE daily_trends (
    -- id: 각 데이터 줄마다 붙는 고유 번호 (자동으로 생성됩니다)
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- date: 분석한 날짜 (예: 2026-01-14)
    date DATE NOT NULL,
    
    -- keyword: 검색한 단어 (예: 두바이 쫀득 쿠키)
    keyword TEXT NOT NULL,
    
    -- video_count: 해당 날짜에 유튜브에 새로 올라온 영상 개수
    video_count INT,
    
    -- total_views: 그날 올라온 영상들의 총 조회수를 다 합친 값
    total_views BIGINT,
    
    -- total_likes: 그날 올라온 영상들의 총 좋아요를 다 합친 값
    total_likes BIGINT,
    
    -- total_comments: 그날 올라온 영상들의 총 댓글을 다 합친 값
    total_comments BIGINT,
    
    -- created_at: 이 데이터가 언제 DB에 기록되었는지 기록하는 시간 (자동 생성)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()), 
    
    -- [중복 방지] 똑같은 날짜에 똑같은 키워드 데이터가 두 번 들어오지 않도록 막아줍니다.
    UNIQUE(date, keyword)
);

-- [속도 향상] 데이터를 나중에 빨리 찾을 수 있게 날짜와 키워드에 '이름표(인덱스)'를 붙여줍니다.
CREATE INDEX idx_daily_trends_date ON daily_trends(date);
CREATE INDEX idx_daily_trends_keyword ON daily_trends(keyword);
