-- youtube_comments 테이블 생성
-- 유튜브 영상의 댓글 및 메타데이터를 저장합니다.

CREATE TABLE IF NOT EXISTS youtube_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comment_id TEXT UNIQUE NOT NULL,          -- 유튜브 고유 댓글 ID
  video_id TEXT NOT NULL,                  -- 유튜브 영상 ID
  author TEXT,                             -- 작성자명
  text TEXT,                               -- 댓글 본문
  published_at TIMESTAMPTZ,                -- 댓글 작성일
  like_count INTEGER DEFAULT 0,            -- 좋아요 수
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 영상 ID 및 작성일 기준 인덱스
CREATE INDEX IF NOT EXISTS idx_yt_video_id ON youtube_comments (video_id);
CREATE INDEX IF NOT EXISTS idx_yt_published_at ON youtube_comments (published_at);
