-- review_analysis_results 테이블 생성
-- 정제된 리뷰에서 추출된 핵심 메타데이터를 저장합니다.

CREATE TABLE IF NOT EXISTS review_analysis_result (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id BIGINT REFERENCES blog_review(id) ON DELETE CASCADE,
  region TEXT,
  product_price INTEGER,                   -- 텍스트에서 정수형(INTEGER)으로 변경
  price_feedback TEXT,
  taste_rating TEXT,
  visit_again TEXT,
  visit_reason TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_review_idx ON review_analysis_result (review_id);
