-- 네이버 블로그 검색 결과 데이터를 저장하기 위한 테이블 생성 스키마
-- Supabase Dashboard -> SQL Editor에 복사하여 실행하세요.

CREATE TABLE naver_blog_trends (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,                                     -- 분석 기준일
    keyword TEXT NOT NULL,                                 -- 검색 키워드
    total_count INT NOT NULL,                             -- 블로그 검색 결과 총 건수
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()), -- 기록 생성 시간
    
    -- 동일 날짜와 키워드에 대해 중복 데이터를 방지하기 위한 제약 조건
    UNIQUE(date, keyword)
);

-- 인덱스 추가 (검색 속도 향상)
CREATE INDEX idx_naver_blog_trends_date ON naver_blog_trends(date);
CREATE INDEX idx_naver_blog_trends_keyword ON naver_blog_trends(keyword);
