CREATE TABLE realtime_subway_positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    subway_id VARCHAR(10),
    subway_name VARCHAR(50),
    station_id VARCHAR(10),
    station_name VARCHAR(50),
    train_number VARCHAR(20),
    last_reception_date VARCHAR(14),
    reception_time TIMESTAMP WITHOUT TIME ZONE,
    up_down_line INTEGER,
    terminal_station_id VARCHAR(10),
    terminal_station_name VARCHAR(50),
    train_status INTEGER,
    express_type INTEGER,
    is_last_train INTEGER
);

-- Optional: Add index for performance on common queries
CREATE INDEX idx_realtime_subway_time ON realtime_subway_positions (reception_time);
CREATE INDEX idx_realtime_subway_line ON realtime_subway_positions (subway_name);
