-- blog_reviews 테이블 생성
-- 네이버 블로그 및 인스타그램에서 수집된 리뷰 데이터를 저장합니다.

CREATE TABLE IF NOT EXISTS blog_reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT,                              -- 게시글 제목
  link TEXT UNIQUE,                        -- 게시글 원본 링크 (중복 방지용 UNIQUE 제약 조건)
  postdate TEXT,                           -- 게시일자
  address TEXT,                            -- 추출된 지역/주소 정보
  raw_content TEXT,                        -- 수집된 원본 본문 텍스트
  clean_content TEXT,                      -- 정규화 처리된 본문 텍스트
  ai_analysis JSONB,                       -- Gemini AI를 통한 분석 결과 (지역, 가격, 리뷰 요약 등)
  created_at TIMESTAMPTZ DEFAULT NOW()     -- 데이터 생성 일시
);

-- 인덱스 생성 (검색 성능 향상)
CREATE INDEX IF NOT EXISTS idx_blog_reviews_postdate ON blog_reviews (postdate);
CREATE INDEX IF NOT EXISTS idx_blog_reviews_address ON blog_reviews (address);
