-- Create table for storing real-time subway train positions
CREATE TABLE realtime_subway_positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line_id VARCHAR(50) NOT NULL,              -- subwayId: 지하철 호선 ID
    line_name VARCHAR(100) NOT NULL,           -- subwayNm: 지하철 호선명
    station_id VARCHAR(50) NOT NULL,           -- statnId: 지하철 역 ID
    station_name VARCHAR(100) NOT NULL,        -- statnNm: 지하철 역명
    train_number VARCHAR(50) NOT NULL,         -- trainNo: 열차 번호
    last_rec_date VARCHAR(20),                 -- lastRecptnDt: 최종 수신 날짜
    last_rec_time VARCHAR(20),                 -- recptnDt: 최종 수신 시간
    direction_type VARCHAR(10),                -- updnLine: 0:상행/내선, 1:하행/외선
    dest_station_id VARCHAR(50),               -- statnTid: 종착역 ID
    dest_station_name VARCHAR(100),            -- statnTnm: 종착역명
    train_status VARCHAR(10),                  -- trainSttus: 0:진입, 1:도착, 2:출발, 3:전전역출발 등
    is_express VARCHAR(10),                    -- directAt: 1:급행, 0:아님, 7:특급
    is_last_train BOOLEAN,                     -- lstcarAt: 막차 여부 (0:아님, 1:막차) - API returns '0'/'1', stored as boolean
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() -- 데이터 적재 시간
);

-- Optional: Create indexes for frequent queries
CREATE INDEX idx_realtime_positions_line_id ON realtime_subway_positions (line_id);
CREATE INDEX idx_realtime_positions_station_id ON realtime_subway_positions (station_id);
CREATE INDEX idx_realtime_positions_created_at ON realtime_subway_positions (created_at);
