-- 네이버 블로그 일별 포스팅 수 저장을 위한 테이블 스키마
CREATE TABLE IF NOT EXISTS public.naver_blog_counts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword TEXT NOT NULL,
    target_date DATE NOT NULL,
    post_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- 동일 키워드와 날짜에 대해 중복 데이터가 쌓이지 않도록 유니크 제약 조건 추가
    CONSTRAINT naver_blog_counts_keyword_date_key UNIQUE (keyword, target_date)
);

-- 인덱스 추가 (조회 성능 향상)
CREATE INDEX IF NOT EXISTS idx_naver_blog_counts_keyword_date ON public.naver_blog_counts(keyword, target_date);
